services:
  php:
    container_name: firaga-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      ENV: local
      DB_CONNECTION: sqlite
      PHP_IDE_CONFIG: "serverName=laravel"
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./:/var/www:cached
      - firaga_storage:/var/www/storage
      - firaga_bootstrap_cache:/var/www/bootstrap/cache
      - firaga_vendor:/var/www/vendor
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"

  node:
    image: node:20-alpine
    container_name: firaga-node
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - firaga_node_modules:/var/www/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - php

volumes:
  firaga_storage:
  firaga_bootstrap_cache:
  firaga_vendor:
  firaga_node_modules: