FROM nginx:alpine

RUN mkdir -p /etc/nginx/snippets
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/laravel.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx/snippets/fastcgi-php.conf /etc/nginx/snippets/

EXPOSE 80

CMD ["nginx"]