<?php

namespace App\Filament\Pages;

use Filament\Pages\Auth\Login;

class Authentication extends Login
{
    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        if (app()->environment('local', 'staging')) {
            $this->form->fill([
                'email' => 'admin@admin.com',
                'password' => 'admin',
                'remember' => true,
            ]);
        }
    }
}
