name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      CACHE_KEY: ${{ steps.cache.outputs.key }}
      PHP_VERSION: ${{ steps.config.outputs.PHP_VERSION }}
      PHP_EXTENSIONS: ${{ steps.config.outputs.PHP_EXTENSIONS }}
      PHP_INI_PROPERTIES: ${{ steps.config.outputs.PHP_INI_PROPERTIES }}
      COMPOSER_FLAGS: ${{ steps.config.outputs.COMPOSER_FLAGS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set build config
        id: config
        run: |
          echo "PHP_VERSION=8.4" >> "$GITHUB_OUTPUT"
          echo "PHP_EXTENSIONS=mbstring,pdo,pdo_pgsql,xml,ctype,fileinfo,json,curl,openssl,dom,zip" >> "$GITHUB_OUTPUT"
          echo "PHP_INI_PROPERTIES=post_max_size=256M,upload_max_filesize=256M" >> "$GITHUB_OUTPUT"
          echo "COMPOSER_FLAGS=--prefer-dist --optimize-autoloader" >> "$GITHUB_OUTPUT"

      - name: Create cache key
        id: cache
        env:
          RUNNER_OS: ${{ runner.os }}
          RUNNER_ARCH: ${{ runner.arch }}
          HASHED_COMPOSER_LOCK: ${{ hashFiles('composer.lock') }}
        run: |
          os_lower=$(echo ${RUNNER_OS} | tr '[:upper:]' '[:lower:]')
          arch_lower=$(echo ${RUNNER_ARCH} | tr '[:upper:]' '[:lower:]')
          echo "key=${os_lower}-${arch_lower}-composer-${HASHED_COMPOSER_LOCK}" >> "$GITHUB_OUTPUT"

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: 8.4
          extensions: mbstring,pdo,pdo_pgsql,xml,ctype,fileinfo,json,curl,openssl,dom,zip
          ini-values: post_max_size=256M,upload_max_filesize=256M
          coverage: none
          tools: composer:v2

      - name: Add Flux credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install composer dependencies
        uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # v3.0.0
        with:
          composer-options: '--prefer-dist --optimize-autoloader'
          custom-cache-key: ${{ steps.cache.outputs.key }}

  pint:
    name: Pint
    needs: [setup]
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      contents: read
    uses: ./.github/workflows/_pint.yml
    with:
      PHP_VERSION: ${{ needs.setup.outputs.PHP_VERSION }}
      PHP_EXTENSIONS: ${{ needs.setup.outputs.PHP_EXTENSIONS }}
      PHP_INI_PROPERTIES: ${{ needs.setup.outputs.PHP_INI_PROPERTIES }}
      COMPOSER_FLAGS: ${{ needs.setup.outputs.COMPOSER_FLAGS }}
      CACHE_KEY: ${{ needs.setup.outputs.CACHE_KEY }}

  rector:
    name: Rector
    needs: [setup]
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      contents: read
    uses: ./.github/workflows/_rector.yml
    with:
      PHP_VERSION: ${{ needs.setup.outputs.PHP_VERSION }}
      PHP_EXTENSIONS: ${{ needs.setup.outputs.PHP_EXTENSIONS }}
      PHP_INI_PROPERTIES: ${{ needs.setup.outputs.PHP_INI_PROPERTIES }}
      COMPOSER_FLAGS: ${{ needs.setup.outputs.COMPOSER_FLAGS }}
      CACHE_KEY: ${{ needs.setup.outputs.CACHE_KEY }}

  pest:
    name: Pest
    needs: [setup]
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      contents: read
    uses: ./.github/workflows/_pest.yml
    with:
      PHP_VERSION: ${{ needs.setup.outputs.PHP_VERSION }}
      PHP_EXTENSIONS: ${{ needs.setup.outputs.PHP_EXTENSIONS }}
      PHP_INI_PROPERTIES: ${{ needs.setup.outputs.PHP_INI_PROPERTIES }}
      COMPOSER_FLAGS: ${{ needs.setup.outputs.COMPOSER_FLAGS }}
      CACHE_KEY: ${{ needs.setup.outputs.CACHE_KEY }}
    secrets:
      FLUX_USERNAME: ${{ secrets.FLUX_USERNAME }}
      FLUX_LICENSE_KEY: ${{ secrets.FLUX_LICENSE_KEY }}
